name: rx_pack
description: Extension for Dart's Stream class that adds additional functionality.
version: 1.0.2
repository: https://github.com/cvalab/rx_pack.git

environment:
  sdk: ">=3.0.0 <4.0.0"

#dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
